theme: jekyll-theme-minimal
plugins:
- jekyll-seo-tag

title: AI in Cybersecurity Education 
description: Faculty Development Summer Institute 2026


show_downloads: false

sass:
  quiet_deps: true
  silence_deprecations:
    - import
